### NUMPY: Package for Multidimensional array

In [1]:
import numpy as np

In [2]:
simple_list=[3,5,6]
np.array(simple_list)

array([3, 5, 6])

In [5]:
d=np.array([2,5,10])
d

array([ 2,  5, 10])

In [7]:
list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [10]:
np.arange(5,78)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77])

In [11]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
np.arange(1,35,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [14]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
np.ones((2,5,),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [35]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [39]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [40]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [49]:
np.random.rand(3,5) 

array([[0.29111407, 0.96508724, 0.54560885, 0.76649454, 0.68946561],
       [0.29223757, 0.07338026, 0.99506817, 0.39219318, 0.02617125],
       [0.00952442, 0.41905893, 0.71483602, 0.02420979, 0.86160397]])

In [51]:
arr=np.random.randn(2,4)
arr

array([[-1.56256838,  0.53293372,  0.21408086,  0.55158898],
       [ 0.68610533, -0.04894271, -0.91694857, -0.57478369]])

In [52]:
np.random.randint(22,150)

130

In [81]:
sample_array=np.arange(40)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [82]:
sample_array.reshape(5,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [83]:
sample_array.reshape(3,8)

ValueError: cannot reshape array of size 40 into shape (3,8)

In [62]:
rand_array=np.random.randint(0,10,50)
rand_array

array([6, 7, 8, 6, 6, 1, 5, 4, 9, 1, 0, 9, 1, 2, 6, 2, 7, 9, 4, 8, 6, 9,
       6, 1, 8, 6, 9, 9, 0, 0, 8, 3, 2, 4, 4, 0, 3, 7, 2, 3, 3, 4, 0, 4,
       9, 3, 2, 5, 3, 1])

In [67]:
rand_array.argmax()

8

In [69]:
rand_array.max()

9

In [71]:
a=np.eye(9)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [72]:
a.T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [73]:
a=np.random.rand(2,3)
a

array([[0.0959823 , 0.45533874, 0.02659948],
       [0.75518239, 0.35151822, 0.26388588]])

In [74]:
a.T

array([[0.0959823 , 0.75518239],
       [0.45533874, 0.35151822],
       [0.02659948, 0.26388588]])

In [87]:
sample_array=np.arange(10,22)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [88]:
sample_array[0]

10

In [89]:
sample_array[1:5]

array([11, 12, 13, 14])

In [91]:
sample_array[2:3]=100
sample_array

array([ 10,  11, 100,  13,  14,  15,  16,  17,  18,  19,  20,  21])

In [92]:
sample_array=np.arange(10,20)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [93]:
subset_sample_array=sample_array[0:5]
subset_sample_array

array([10, 11, 12, 13, 14])

In [94]:
subset_sample_array[:]=1008
subset_sample_array

array([1008, 1008, 1008, 1008, 1008])

### Two-Dimensional Array

In [95]:
import numpy as np

In [96]:
sample_matrix=np.array([[10,20,30],[40,50,60],[70,80,90]])
sample_matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [98]:
sample_matrix[1,2]

60

In [100]:
sample_matrix[2,:]

array([70, 80, 90])

In [101]:
sample_matrix[1]

array([40, 50, 60])

In [103]:
sample_matrix[:,(1,2)]

array([[20, 30],
       [50, 60],
       [80, 90]])



### Selection Techniques

In [105]:
sample_array=np.arange(1,30)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [106]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [107]:
np.exp(sample_array)  #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12])

In [108]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [109]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583])

In [110]:
np.max(sample_array)

29

In [111]:
np.min(sample_array)

1

In [112]:
np.argmax(sample_array)

28

In [113]:
np.argmin(sample_array)

0

In [114]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841])

In [115]:
np.std(sample_array)

8.366600265340756

In [116]:
np.var(sample_array)

70.0

In [117]:
np.mean(sample_array)

15.0

In [119]:
array=np.random.randn(3,4)
array

array([[ 7.30029830e-01, -1.24650799e+00, -3.75918636e-01,
         5.19240552e-01],
       [-1.04882997e+00,  1.05128835e-03,  1.05258843e+00,
        -7.20641914e-01],
       [-1.31496113e-01, -7.59136753e-01, -3.33180317e-01,
         7.93312045e-02]])

In [124]:
np.round(array,decimals=3)

array([[ 7.300e-01, -1.247e+00, -3.760e-01,  5.190e-01],
       [-1.049e+00,  1.000e-03,  1.053e+00, -7.210e-01],
       [-1.310e-01, -7.590e-01, -3.330e-01,  7.900e-02]])

In [127]:
sports=np.array(['golf','cricket','fball','hockey','cricket','badminton'])
np.unique(sports)

array(['badminton', 'cricket', 'fball', 'golf', 'hockey'], dtype='<U9')

### Pandas dataframe and indexing

In [128]:
import pandas as pd
import numpy as np

In [130]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [131]:
sports1['football']

2

In [135]:
sports2=pd.Series([11,2,5,6,8],index=['cricket','baseball','hockey','golf','football'])
sports2

cricket     11
baseball     2
hockey       5
golf         6
football     8
dtype: int64

In [136]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      10.0
golf          10.0
hockey         NaN
dtype: float64

In [140]:
df1=pd.DataFrame(np.random.rand(8,7),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5 score6 score7'.split())
df1

score1    score2    score3    score4    score5    score6    score7
A  0.177789  0.865471  0.783864  0.328054  0.149260  0.468153  0.015598
B  0.729772  0.602465  0.350925  0.508900  0.893704  0.938858  0.379855
C  0.392808  0.224561  0.528917  0.117947  0.073442  0.636271  0.731191
D  0.818215  0.465521  0.219929  0.531365  0.608670  0.785379  0.118894
E  0.676622  0.368351  0.434784  0.608350  0.787152  0.448650  0.231813
F  0.817864  0.829577  0.091339  0.133937  0.596598  0.666584  0.120456
G  0.201351  0.181775  0.561660  0.279703  0.498860  0.737407  0.089608
H  0.489585  0.584677  0.812975  0.547749  0.051072  0.721645  0.468681

In [143]:
df1["score1"]

A    0.177789
B    0.729772
C    0.392808
D    0.818215
E    0.676622
F    0.817864
G    0.201351
H    0.489585
Name: score1, dtype: float64

In [147]:
df1[["score1","score2","score3"]]

score1    score2    score3
A  0.177789  0.865471  0.783864
B  0.729772  0.602465  0.350925
C  0.392808  0.224561  0.528917
D  0.818215  0.465521  0.219929
E  0.676622  0.368351  0.434784
F  0.817864  0.829577  0.091339
G  0.201351  0.181775  0.561660
H  0.489585  0.584677  0.812975

In [148]:
df1['score8']=df1['score1']+df1['score2']+df1['score3']
df1

score1    score2    score3    score4    score5    score6    score7  \
A  0.177789  0.865471  0.783864  0.328054  0.149260  0.468153  0.015598   
B  0.729772  0.602465  0.350925  0.508900  0.893704  0.938858  0.379855   
C  0.392808  0.224561  0.528917  0.117947  0.073442  0.636271  0.731191   
D  0.818215  0.465521  0.219929  0.531365  0.608670  0.785379  0.118894   
E  0.676622  0.368351  0.434784  0.608350  0.787152  0.448650  0.231813   
F  0.817864  0.829577  0.091339  0.133937  0.596598  0.666584  0.120456   
G  0.201351  0.181775  0.561660  0.279703  0.498860  0.737407  0.089608   
H  0.489585  0.584677  0.812975  0.547749  0.051072  0.721645  0.468681   

     score8  
A  1.827124  
B  1.683162  
C  1.146287  
D  1.503665  
E  1.479757  
F  1.738779  
G  0.944785  
H  1.887237

In [176]:
df2={'ID':['100','101','103','110','112'],'Name':['sagar','akash','ritik','kailas','vedant'],'profit':[10,30,50,70,90],'loss':[10,10,10,10,10]}
df=pd.DataFrame(df2)
df

ID    Name  profit  loss
0  100   sagar      10    10
1  101   akash      30    10
2  103   ritik      50    10
3  110  kailas      70    10
4  112  vedant      90    10

In [177]:
df["ID"]

0    100
1    101
2    103
3    110
4    112
Name: ID, dtype: object

In [157]:
df[["ID","Name"]]

ID    Name
0  100   sagar
1  101   akash
2  103   ritik
3  110  kailas
4  112  vedant

In [169]:
df.drop(3)

Name  profit  loss
0   sagar      10    10
1   akash      30    10
2   ritik      50    10
4  vedant      90    10

In [178]:
df=df.drop("ID",axis=1)

In [179]:
df

Name  profit  loss
0   sagar      10    10
1   akash      30    10
2   ritik      50    10
3  kailas      70    10
4  vedant      90    10